{"uuid": "2cbc0f20-a6f0-4bd0-b1e3-3e9b4d6aaead", "children": ["fc0985e5-fc72-49ec-834d-3423cd723c8c"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102c516d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))\n", "trace": "  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/hehuaimei/PycharmProjects/python_appium/po_appium_2/conftest.py\", line 74, in driver\n    app_driver = webdriver.Remote(\"http://localhost:4723/wd/hub\",desired_caps)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 151, in __init__\n    super().__init__(\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 752, in urlopen\n    return self.urlopen(\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 752, in urlopen\n    return self.urlopen(\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 752, in urlopen\n    return self.urlopen(\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 724, in urlopen\n    retries = retries.increment(\n  File \"/Users/hehuaimei/PycharmProjects/untitled/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1607760030220, "stop": 1607760030300}], "start": 1607760030220, "stop": 1607760031000}